# Falco Custom Rules - Secret Access Monitoring
# Monitoring pristupa Kubernetes secretima i servisnim računima
apiVersion: v1
kind: ConfigMap
metadata:
  name: falco-rules-secret-access
  namespace: falco
  labels:
    app.kubernetes.io/name: falco
    app.kubernetes.io/component: rules
data:
  secret-access-monitor.yaml: |
    # Monitoring pristupa Kubernetes service account tokenima
    - rule: Semaphore Secret File Read
      desc: >
        Monitoriše pristup Kubernetes service account tokenima i
        ostalim osjetljivim fajlovima u Semaphore namespace-u.
      condition: >
        open_read and container and
        fd.name startswith /run/secrets/kubernetes.io/ and
        k8s.ns.name = "semaphore" and
        not proc.name in (guard, controller, front, node, beam.smp)
      output: >
        Secret file read detected
        (user=%user.name user_uid=%user.uid process=%proc.name
        parent=%proc.pname file=%fd.name pod=%k8s.pod.name
        namespace=%k8s.ns.name container=%container.name
        image=%container.image.repository)
      priority: WARNING
      source: syscall
      tags: [filesystem, secrets, semaphore, mitre_credential_access]

    # Detekcija pristupa environment varijablama sa secretima
    - rule: Environment Secret Access
      desc: Detekcija pristupa environment varijablama koje sadrže secrete
      condition: >
        open_read and container and
        k8s.ns.name = "semaphore" and
        fd.name = "/proc/self/environ" and
        not proc.name in (guard, controller, front, node, mix)
      output: >
        Process reading environment variables (potential secret access)
        (user=%user.name process=%proc.name file=%fd.name
        pod=%k8s.pod.name namespace=%k8s.ns.name)
      priority: NOTICE
      source: syscall
      tags: [filesystem, secrets, semaphore, mitre_credential_access]

    # Detekcija modifikacije secret mount-ova
    - rule: Secret Mount Modification Attempt
      desc: Detekcija pokušaja modifikacije mounted secretsa
      condition: >
        (open_write or unlink) and container and
        fd.name startswith /run/secrets/ and
        k8s.ns.name = "semaphore"
      output: >
        Attempt to modify secret mount
        (user=%user.name process=%proc.name file=%fd.name
        pod=%k8s.pod.name namespace=%k8s.ns.name)
      priority: CRITICAL
      source: syscall
      tags: [filesystem, secrets, tampering, semaphore, mitre_defense_evasion]

    # Detekcija pristupa osjetljivim config fajlovima
    - rule: Sensitive Config File Access
      desc: Detekcija pristupa osjetljivim konfiguracijskim fajlovima
      condition: >
        open_read and container and
        k8s.ns.name = "semaphore" and
        (
          fd.name contains "password" or
          fd.name contains "credential" or
          fd.name contains ".pem" or
          fd.name contains ".key" or
          fd.name contains ".crt"
        ) and
        not fd.name startswith /etc/ssl/
      output: >
        Access to sensitive configuration file
        (user=%user.name process=%proc.name file=%fd.name
        pod=%k8s.pod.name namespace=%k8s.ns.name)
      priority: WARNING
      source: syscall
      tags: [filesystem, secrets, semaphore, mitre_credential_access]

    # Detekcija kubectl exec pokušaja
    - rule: Kubectl Exec into Semaphore Pod
      desc: Detekcija kubectl exec komandi u Semaphore podove
      condition: >
        spawned_process and container and
        k8s.ns.name = "semaphore" and
        proc.pname = "runc" and
        proc.name in (bash, sh, ash)
      output: >
        Kubectl exec detected in production pod
        (user=%user.name command=%proc.cmdline pod=%k8s.pod.name
        namespace=%k8s.ns.name container=%container.name)
      priority: WARNING
      source: syscall
      tags: [container, exec, semaphore, mitre_execution]
