# External Secrets Operator - integracija sa cloud secret management sistemima
# Podržava: AWS Secrets Manager, GCP Secret Manager, Azure Key Vault, HashiCorp Vault
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: gcp-secret-store
  namespace: semaphore
spec:
  provider:
    gcpsm:
      projectID: semaphore-prod
      auth:
        workloadIdentity:
          clusterLocation: europe-west1
          clusterName: semaphore-cluster
          serviceAccountRef:
            name: external-secrets-sa
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: database-credentials
  namespace: semaphore
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-secret-store
    kind: SecretStore
  target:
    name: database-secret
    creationPolicy: Owner
  data:
  - secretKey: username
    remoteRef:
      key: semaphore-db-username
  - secretKey: password
    remoteRef:
      key: semaphore-db-password
---
# AWS Secrets Manager primjer
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: aws-secret-store
  namespace: semaphore
spec:
  provider:
    aws:
      service: SecretsManager
      region: eu-central-1
      auth:
        jwt:
          serviceAccountRef:
            name: external-secrets-sa
