# Sealed Secrets - enkriptirani secrets koji se mogu sigurno commitovati u Git
# Koristi asimetri훾nu enkripciju - samo Sealed Secrets controller mo탑e dekriptovati
#
# Instalacija:
# helm repo add sealed-secrets https://bitnami-labs.github.io/sealed-secrets
# helm install sealed-secrets sealed-secrets/sealed-secrets -n kube-system
#
# Kreiranje sealed secret-a:
# kubeseal --format yaml < secret.yaml > sealed-secret.yaml
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: database-credentials
  namespace: semaphore
spec:
  encryptedData:
    # Ovi podaci su enkriptirani sa javnim klju훾em klastera
    # Samo Sealed Secrets controller mo탑e dekriptovati
    username: AgBy3i4OJSWK+PiTySYZZA9rO43cGDEq...
    password: AgBy3i4OJSWK+PiTySYZZA9rO43cGDEq...
  template:
    metadata:
      name: database-credentials
      namespace: semaphore
      labels:
        app: semaphore
        component: database
    type: Opaque
---
# Primjer originalnog secret-a PRIJE enkriptovanja
# NIKADA NE COMMITUJTE OVAJ FAJL - samo za lokalnu upotrebu
# apiVersion: v1
# kind: Secret
# metadata:
#   name: database-credentials
#   namespace: semaphore
# type: Opaque
# stringData:
#   username: semaphore_user
#   password: super-secret-password-123
