apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: siem
  labels:
    app: elasticsearch
spec:
  type: ClusterIP
  clusterIP: None  # Headless service za StatefulSet
  ports:
  - port: 9200
    name: http
    protocol: TCP
  - port: 9300
    name: transport
    protocol: TCP
  selector:
    app: elasticsearch
---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-http
  namespace: siem
  labels:
    app: elasticsearch
spec:
  type: ClusterIP
  ports:
  - port: 9200
    name: http
    protocol: TCP
    targetPort: 9200
  selector:
    app: elasticsearch
